### ISSUE TITLE
UberGallery 3.0 Roadmap

### ISSUE THREAD

**Issue by PHLAK** [UberGallery/UberGallery#58]
The purpose of this issue is to serve as a roadmap for UberGallery 3.0 features and discussions.  Please feel free to suggest any ideas below and +1 the ones you like.

**NOTE: This roadmap is a work in progress and isn't final.  It can, and likely will, change over time as the ideas and desires of the users and myself are flushed out.**

-----

The Vision
=========

UberGallery 3.0 is a flat-file (no database) web photo gallery.  Installation is as simple as uploading the UberGallery files and adding your images to a directory.  Basic customizations will be available via editing of a simple configuration file and plug-ins.  For more advanced users, UberGallery's underlying code should be simple to understand and easy to implement within a parent project using modern PHP tools (i.e. Composer) and techniques.

Requirements
===========
  - [ ] Drag-and-drop installation
  - [ ] Supported file types: PNG, JPEG, GIF
  - [ ] Multiple gallery support
  - [ ] Plugins

**Comment by unquietwiki** [comment]
Looking forward to multi-gallery support. Had tried downloading 3.0 branch to test things out, but saw its still using some TravisCI thing.  My website was using a mess of stuff from http://metroui.org.ua/ for a while, but I still like the theme concepts it has: might be usable in a future theme?

**Comment by unquietwiki** [comment]
Also, I've been using http://sye.dk/sfpg/ for my album needs the past year or two. Its the most comparable to this project, in terms of functionality and features. Was able to customize my copy some, but can be difficult after updates (which appears to have become infrequent).
